---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: posgres-db
    author: intelliqit
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
     name: postgres
...

